### ISSUE TITLE
how to use in ionic 2

### ISSUE THREAD

**Issue by jose2007kj** [Guutong/cordova-plugin-android-native-pdfviewer#1]
sir,how shall i use this in ionic2

**Comment by Guutong** [comment]
@jose2007kj 
your try install plugin first use command line
`ionic plugin add cordova-plugin-android-native-pdfviewer`

.html 
`<button myitem (click)='openPdfFromUrl();'>CLICK</button>`

.ts
before @Componant
`declare var AndroidNativePdfViewer: any`

Add function open pdf in page class

```
openPdfFromUrl() {
      var options = {
        headerColor: "#000000",
        showScroll: true,
        swipeHorizontal: false
      };
      var url = ""; // <==== url pdf
      AndroidNativePdfViewer.openPdfUrl(url,
        "Test",
        options,
        function (success) {
          console.log("AndroidNativePdfViewer success");
        }, function (error) {
          console.error("AndroidNativePdfViewer error : " + error);
        });
 }
```

see at page home https://github.com/Guutong/ionic2Example

**Comment by jose2007kj** [comment]
@Guutong  thanks a lot sir.........i will check

**Comment by msanprasdo** [comment]
i'm not using ionic but jQueryMobile.
how i can apply it using jQueryMobile
